<?php

/**
 * BaseGranitMetas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $obj_id
 * @property string $content
 * @property GranitObject $GranitObject
 * 
 * @method integer      getObjId()        Returns the current record's "obj_id" value
 * @method string       getContent()      Returns the current record's "content" value
 * @method GranitObject getGranitObject() Returns the current record's "GranitObject" value
 * @method GranitMetas  setObjId()        Sets the current record's "obj_id" value
 * @method GranitMetas  setContent()      Sets the current record's "content" value
 * @method GranitMetas  setGranitObject() Sets the current record's "GranitObject" value
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitMetas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_metas');
        $this->hasColumn('obj_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranitObject', array(
             'local' => 'obj_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}