<?php

/**
 * BaseGranitComplect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $GranitProd_complect
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method Doctrine_Collection getGranitProdComplect()  Returns the current record's "GranitProd_complect" collection
 * @method GranitComplect      setName()                Sets the current record's "name" value
 * @method GranitComplect      setGranitProdComplect()  Sets the current record's "GranitProd_complect" collection
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitComplect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_complect');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GranitProd_complect', array(
             'local' => 'id',
             'foreign' => 'complect_id'));
    }
}