<?php

/**
 * BaseGranitObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sub_cat_id
 * @property boolean $active
 * @property GranitSub_cat $GranitSub_cat
 * @property Doctrine_Collection $Prod
 * @property Doctrine_Collection $Inf
 * @property Doctrine_Collection $Photo
 * @property Doctrine_Collection $Metas
 * 
 * @method integer             getSubCatId()      Returns the current record's "sub_cat_id" value
 * @method boolean             getActive()        Returns the current record's "active" value
 * @method GranitSub_cat       getGranitSubCat()  Returns the current record's "GranitSub_cat" value
 * @method Doctrine_Collection getProd()          Returns the current record's "Prod" collection
 * @method Doctrine_Collection getInf()           Returns the current record's "Inf" collection
 * @method Doctrine_Collection getPhoto()         Returns the current record's "Photo" collection
 * @method Doctrine_Collection getMetas()         Returns the current record's "Metas" collection
 * @method GranitObject        setSubCatId()      Sets the current record's "sub_cat_id" value
 * @method GranitObject        setActive()        Sets the current record's "active" value
 * @method GranitObject        setGranitSubCat()  Sets the current record's "GranitSub_cat" value
 * @method GranitObject        setProd()          Sets the current record's "Prod" collection
 * @method GranitObject        setInf()           Sets the current record's "Inf" collection
 * @method GranitObject        setPhoto()         Sets the current record's "Photo" collection
 * @method GranitObject        setMetas()         Sets the current record's "Metas" collection
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_object');
        $this->hasColumn('sub_cat_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranitSub_cat', array(
             'local' => 'sub_cat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GranitProduction as Prod', array(
             'local' => 'id',
             'foreign' => 'obj_id'));

        $this->hasMany('GranitInformation as Inf', array(
             'local' => 'id',
             'foreign' => 'obj_id'));

        $this->hasMany('GranitPhoto as Photo', array(
             'local' => 'id',
             'foreign' => 'obj_id'));

        $this->hasMany('GranitMetas as Metas', array(
             'local' => 'id',
             'foreign' => 'obj_id'));
    }
}