<?php

/**
 * BaseGranitProd_complect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $prod_id
 * @property integer $complect_id
 * @property GranitComplect $GranitComplect
 * @property GranitProduction $GranitProduction
 * 
 * @method integer             getProdId()           Returns the current record's "prod_id" value
 * @method integer             getComplectId()       Returns the current record's "complect_id" value
 * @method GranitComplect      getGranitComplect()   Returns the current record's "GranitComplect" value
 * @method GranitProduction    getGranitProduction() Returns the current record's "GranitProduction" value
 * @method GranitProd_complect setProdId()           Sets the current record's "prod_id" value
 * @method GranitProd_complect setComplectId()       Sets the current record's "complect_id" value
 * @method GranitProd_complect setGranitComplect()   Sets the current record's "GranitComplect" value
 * @method GranitProd_complect setGranitProduction() Sets the current record's "GranitProduction" value
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitProd_complect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_prod_complect');
        $this->hasColumn('prod_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('complect_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranitComplect', array(
             'local' => 'complect_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GranitProduction', array(
             'local' => 'prod_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}