<?php

/**
 * BaseGranitCat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property text $shortcart
 * @property Doctrine_Collection $Sub_cat
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method text                getShortcart() Returns the current record's "shortcart" value
 * @method Doctrine_Collection getSubCat()    Returns the current record's "Sub_cat" collection
 * @method GranitCat           setName()      Sets the current record's "name" value
 * @method GranitCat           setShortcart() Sets the current record's "shortcart" value
 * @method GranitCat           setSubCat()    Sets the current record's "Sub_cat" collection
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitCat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_cat');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('shortcart', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GranitSub_cat as Sub_cat', array(
             'local' => 'id',
             'foreign' => 'cat_id'));

        $translit0 = new Doctrine_Template_Translit(array(
             'feilds' => 'name',
             ));
        $this->actAs($translit0);
    }
}