<?php

/**
 * BaseGranitProduction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $obj_id
 * @property string $name
 * @property string $icon
 * @property string $material
 * @property text $complect
 * @property string $price
 * @property GranitObject $GranitObject
 * @property Doctrine_Collection $Complect
 * 
 * @method integer             getObjId()        Returns the current record's "obj_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getIcon()         Returns the current record's "icon" value
 * @method string              getMaterial()     Returns the current record's "material" value
 * @method text                getComplect()     Returns the current record's "complect" value
 * @method string              getPrice()        Returns the current record's "price" value
 * @method GranitObject        getGranitObject() Returns the current record's "GranitObject" value
 * @method Doctrine_Collection getComplect()     Returns the current record's "Complect" collection
 * @method GranitProduction    setObjId()        Sets the current record's "obj_id" value
 * @method GranitProduction    setName()         Sets the current record's "name" value
 * @method GranitProduction    setIcon()         Sets the current record's "icon" value
 * @method GranitProduction    setMaterial()     Sets the current record's "material" value
 * @method GranitProduction    setComplect()     Sets the current record's "complect" value
 * @method GranitProduction    setPrice()        Sets the current record's "price" value
 * @method GranitProduction    setGranitObject() Sets the current record's "GranitObject" value
 * @method GranitProduction    setComplect()     Sets the current record's "Complect" collection
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitProduction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_production');
        $this->hasColumn('obj_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('material', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('complect', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('price', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranitObject', array(
             'local' => 'obj_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GranitProd_complect as Complect', array(
             'local' => 'id',
             'foreign' => 'prod_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $translit0 = new Doctrine_Template_Translit(array(
             'feilds' => 'name',
             ));
        $this->actAs($timestampable0);
        $this->actAs($translit0);
    }
}