<?php

/**
 * BaseGranitInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $obj_id
 * @property string $title
 * @property text $shortcart
 * @property string $icon
 * @property text $content
 * @property GranitObject $GranitObject
 * 
 * @method integer           getObjId()        Returns the current record's "obj_id" value
 * @method string            getTitle()        Returns the current record's "title" value
 * @method text              getShortcart()    Returns the current record's "shortcart" value
 * @method string            getIcon()         Returns the current record's "icon" value
 * @method text              getContent()      Returns the current record's "content" value
 * @method GranitObject      getGranitObject() Returns the current record's "GranitObject" value
 * @method GranitInformation setObjId()        Sets the current record's "obj_id" value
 * @method GranitInformation setTitle()        Sets the current record's "title" value
 * @method GranitInformation setShortcart()    Sets the current record's "shortcart" value
 * @method GranitInformation setIcon()         Sets the current record's "icon" value
 * @method GranitInformation setContent()      Sets the current record's "content" value
 * @method GranitInformation setGranitObject() Sets the current record's "GranitObject" value
 * 
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranitInformation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granit_information');
        $this->hasColumn('obj_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('shortcart', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranitObject', array(
             'local' => 'obj_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $translit0 = new Doctrine_Template_Translit(array(
             'feilds' => 'name',
             ));
        $this->actAs($timestampable0);
        $this->actAs($translit0);
    }
}