<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2002/01/02 13:45:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=granit',
  'username' => 'root',
  'password' => 'nigerniger',
  'name' => 'doctrine',
)),);
