<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2002/01/02 13:45:04
sfConfig::add(array(
  'app_max_objects_on_page' => 21,
  'app_max_objects_on_sub_cat' => 6,
  'app_objects_on_cat_sub_cat' => 9,
  'app_max_objects_on_homepage' => 3,
  'app_default_icon' => 'sample.png',
  'app_default_img' => 'default.jpg',
));
