<?php

/**
 * GranitMetasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitMetasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitMetasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitMetas');
    }
}