<?php

/**
 * GranitComplectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitComplectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitComplectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitComplect');
    }
}