<?php

/**
 * GranitObjectTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitObject');
    }
    public static function PartialObjectsQuery($sub_cat_id=false)
    {
    	$q = Doctrine_Query::create()
		->from('GranitObject o')
		->leftJoin('o.Inf i')
		->leftJoin('o.Prod p');
    	if($sub_cat_id)
    	{
    		$q->where('o.sub_cat_id =?',$sub_cat_id)
    			->leftJoin('o.GranitSub_cat s');
    	}
    	return $q;
    }
    public static function FullObjectQuery($param)
    {
    	$q=self::PartialObjectsQuery()
    		->leftJoin('o.Metas m')
    		->leftJoin('o.Photo ph')
    		->leftJoin('o.GranitSub_cat s')
    		->LeftJoin('s.GranitCat c')
    		->LeftJoin('p.GranitProd_complect pc')
    		->LeftJoin('pc.GranitComplect cp')
    		->Where('o.id=?',$param);
    	return $q;
    }
    public static function ObjectsForSubCatQuery($max = 10,$id)
    {

    	$q = self::PartialObjectsQuery()
    	->LeftJoin('o.GranitSub_cat s')
    	->LeftJoin('s.GranitCat c')
    	->where('o.sub_cat_id = ?', $id)
    	->limit($max);
    	return $q;
    }
    public static function showObject($options=false)
    {
    	if((!$options)||(!$options['obj_id']))
    	{
    		return false;
    	}
    	return self::fullObjectQuery($options['obj_id'])->execute();
    }
}