<?php

/**
 * GranitPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitPhoto');
    }
}