<?php

/**
 * GranitPhoto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GranitPhoto extends BaseGranitPhoto
{
	public function getPhoto()
	{
		return '/photo/'.$this->getObj_id().'/'.$this->getId().'.jpg';
	}
	public function getIcon()
	{
		return '/photo/'.$this->getObj_id().'/icon/'.$this->getId().'.jpg';
	}
}