<?php

/**
 * GranitInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitInformation');
    }
}