<?php

/**
 * GranitSub_cat
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GranitSub_cat extends BaseGranitSub_cat
{
	public function getObjects($max = 10)
	{

		$q = Doctrine_Core::getTable('GranitObject')->ObjectsForSubCatQuery($max,$this->getId())
		->execute();
		return $q;
	}
	public function getObjectsType()
	{
		$q= Doctrine_Core::getTable('GranitObject')->ObjectsForSubCatQuery(1,$this->getId())
		->execute();
		if($q->getLast()->Prod->count())
		{
			return "prod";
		}
		else
		{
			return "inf";
		}
	}	
}