<?php

/**
 * GranitCat
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    granit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GranitCat extends BaseGranitCat
{
	public function getCat_f()
	{
		return mb_substr($this->getName(),0,1,'utf-8');
	}
	public function getCat_b()
	{
		$len=strlen($this->getName())-1;
		return mb_substr($this->getName(),1,$len,'utf-8');
	}
}