<?php

/**
 * GranitProd_complectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GranitProd_complectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GranitProd_complectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GranitProd_complect');
    }
}